### PR TITLE
Add button to connect to any wallet

### PR DESCRIPTION
**Pull request by pgherveou**
Screenshot 2024-12-04 at 11 51 13

### CODE REVIEW

**Comment by smiasojed** [comment]
Should we update `Connect Button` in https://github.com/paritytech/contract-docs/blob/master/docs/tutorial/work-with-a-local-node.md?

**Comment by athei** [comment]
Yeah we should update both pages I think.

**Comment by pgherveou** [comment]
Maybe i'll just change the wording for now ans leave the button as is since the next soc site might not support these kind of custom ja components

**Comment by athei** [comment]
But both buttons were custom js components? So the old one also wouldn't work?

**Review by athei — APPROVED** [review]

**Comment by athei** [comment]
Okay lets not shave the yak for now.

**Pull request merged**
